apiVersion: v1
kind: Secret
metadata:
  name: collectorset-controller
{{- if .Values.labels}}
  labels:
{{ toYaml .Values.labels| indent 4 }}
{{- end }}
  annotations:
    ## keep value false as string, spinnaker's limitation, otherwise spinnaker fails to cast boolean to string
    strategy.spinnaker.io/versioned: "false"
{{- if .Values.annotations }}
{{ toYaml .Values.annotations | indent 4 }}
{{- end }}
type: Opaque
data:
  accessID: {{ required "A valid .Values.accessID entry is required!" .Values.accessID | b64enc }}
  accessKey: {{ required "A valid .Values.accessKey entry is required!" .Values.accessKey | b64enc }}
  account: {{ required "A valid .Values.account entry is required!" .Values.account | b64enc }}
  etcdDiscoveryToken: {{ default "" .Values.etcdDiscoveryToken | b64enc | quote }}
  {{- if .Values.proxyUser }}
  proxyUser: {{ default "" .Values.proxyUser | b64enc }}
  {{- end }}
  {{- if .Values.proxyPass }}
  proxyPass: {{ default "" .Values.proxyPass | b64enc }}
  {{- end }}
