kind: Service
apiVersion: v1
metadata:
  name: collectorset-controller
{{- if .Values.labels}}
  labels:
{{ toYaml .Values.labels| indent 4 }}
{{- end }}
{{- if .Values.annotations }}
  annotations:
{{ toYaml .Values.annotations | indent 4 }}
{{- end }}
spec:
  selector:
    app: collectorset-controller
  ports:
  - protocol: TCP
    port: 50000
    targetPort: 50000
