apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
{{- if .Values.labels}}
{{ toYaml .Values.labels| indent 4 }}
{{- end }}
type: Opaque
data:
  lm_bearer_token: {{ required "A valid .Values.lm.bearer_token entry is required!" .Values.lm.bearer_token | b64enc }}