apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: {{ .Release.Name }}
{{- if .Values.labels}}
{{ toYaml .Values.labels| indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
{{- range $key, $val := .Values.service.ports }}
    - name: {{ $key }}
      port: {{ $val }}
      targetPort: {{ $val }}
{{- end }}
  selector:
    app: {{ .Release.Name }}