apiVersion: v2
description: Automated Kubernetes monitoring
name: argus
version: 0.19.0-devel
kubeVersion: ">= 1.14.0-0"
maintainers:
- name: LogicMonitor
  email: argus@logicmonitor.com
icon: https://logicmonitor.github.io/k8s-helm-charts/lm_logo.png
