image:
  repository: logicmonitor/lm-logs-k8s-fluentd
  pullPolicy: IfNotPresent
  tag: "0.0.12"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

env: {}

resources:
  limits:
    memory: 300Mi
  requests:
    cpu: 100m
    memory: 200Mi

nodeSelector: []
affinity: []
tolerations:
 - operator: Exists

