apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: collectorsets.logicmonitor.com
spec:
  group: logicmonitor.com
  names:
    kind: CollectorSet
    listKind: CollectorSetList
    plural: collectorsets
    singular: collectorset
  scope: Namespaced
  version: v1alpha1
