apiVersion: v2
name: lm-container
description: A Helm chart for Logicmonitor's Kubernetes moniotoring solutions
type: application
version: 1.0.1-rc1
maintainers:
  - name: LogicMonitor
    email: argus@logicmonitor.com
icon: https://vkumbhar94.github.io/helm-charts-replica/lm_logo.png
dependencies:
  - name: argus
    # need to explicitly quote to make it string, else json schema fails
    version: "2.0.0-rc1"
    repository: https://vkumbhar94.github.io/helm-charts-replica
    # uncomment to test umbrella chart in while developing
    # repository: file://../argus
    condition: argus.enabled
    tags:
      - logicmonitor
      - argus
      - monitoring
  - name: collectorset-controller
    # need to explicitly quote to make it string, else json schema fails
    version: "1.0.1-rc1"
    repository: https://vkumbhar94.github.io/helm-charts-replica
    # uncomment to test umbrella chart in while developing
    # repository: file://../collectorset-controller
    condition: collectorset-controller.enabled
    tags:
      - logicmonitor
      - collectorset-controller
      - monitoring
